version: '3.4'
services:
  jenkins:
    build:
      context: jenkins/
    privileged: true
    user: root
    ports:
      - 8081:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - /tmp/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
  master:
    build:
      context: master
    ports:
    - "80:8080"
    environment:
    - JAVA_OPTS=-Xmx2048m
    volumes:
      - /tmp/jenkins-master:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
  worker:
    build:
      context: slave
    environment:
      JAVA_OPTS: "-Xmx2048m"
      JENKINS_MASTER: "http://master:8080"
      JENKINS_NAME: "worker"
      JENKINS_USER: "jenkins"
      JENKINS_PASS: "jenkins"
      JENKINS_RETRY: "10"
    volumes:      
      - /tmp/jenkins-worker:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock