version: '3.4'
services:
  master:
    image: softuni/jenkins-master
    ports:
    - "80:8080"
    environment:
    - JAVA_OPTS=-Xmx2048m
    volumes:
      - /tmp/jenkins-master:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
  worker:
    image: softuni/jenkins-worker
    environment:
      JAVA_OPTS: "-Xmx2048m"
      JENKINS_MASTER: "https://build.softuni.org"
      JENKINS_NAME: "worker"
      JENKINS_USER: "Worker"
      JENKINS_PASS: "qweqwe"
      JENKINS_RETRY: "10"
      JENKINS_DISABLE_SSL_VERIFICATION: "true"
    volumes:
      - /tmp/jenkins-worker:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
