version: '3.4'
services:
  master:
    image: softuni/jenkins-master
    ports:
    - "80:8080"
    environment:
    - JAVA_OPTS=-Xmx2048m
    volumes:
      - /tmp/jenkins-master:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
  worker:
    image: softuni/jenkins-worker
    environment:
      JAVA_OPTS: "-Xmx2048m"
      JENKINS_MASTER: "https://build.softuni.org"
      JENKINS_NAME: "worker"
      JENKINS_USER: "Worker"
      JENKINS_PASS: "slave123"
      JENKINS_RETRY: "10"
      JENKINS_DISABLE_SSL_VERIFICATION: "true"
    volumes:
      - /tmp/jenkins-worker:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
  worker2:
    image: jenkins-worker
    environment:
      JAVA_OPTS: "-Xmx2048m"
      JENKINS_URL: "https://build.softuni.org"
      JENKINS_AGENT_NAME: "DarthVader"
      JENKINS_SECRET: "73197cda8cef35ddd8460aa9d53da98e0b9433d99646aae8ffb69bb34972ee6a"
    volumes:
      - /tmp/jenkins-worker:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
