version: '3.4'
services:
  master:
    image: softuni/jenkins-master
    build:
      context: master
    ports:
    - "80:8080"
    environment:
    - JAVA_OPTS=-Xmx2048m
    volumes:
      - /tmp/jenkins-master:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
  worker:
    image: softuni/jenkins-worker
    build:
      context: worker
    environment:
      JAVA_OPTS: "-Xmx2048m"
      JENKINS_MASTER: "http://master:8080"
      JENKINS_NAME: "worker"
      JENKINS_USER: "jenkins"
      JENKINS_PASS: "jenkins"
      JENKINS_RETRY: "10"
    volumes:
      - /tmp/jenkins-worker:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock