version: '3.4'
services:
  master:
    image: softuni/jenkins-master
    ports:
    - "80:8080"
    environment:
    - JAVA_OPTS=-Xmx2048m
    volumes:
      - /tmp/jenkins-master:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
  worker:
    image: jenkins-worker
    environment:
      JAVA_OPTS: "-Xmx2048m"
      JENKINS_URL: "https://build.softuni.org"
    volumes:
      - /tmp/jenkins-worker:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
